import { defineConfig } from 'vitepress'

export default defineConfig({
	base: '/directix/',
	head: [
		['link', { href: '/directix/logo.svg', rel: 'icon' }],
		['meta', { name: 'theme-color', content: '#42b883' }],
	],

	locales: {
		root: {
			description: 'A Vue directives library for Vue 2 and Vue 3',
			label: 'English',
			lang: 'en',
			themeConfig: {
				darkModeSwitchLabel: 'Theme',
				darkModeSwitchTitle: 'Switch to dark theme',
				docFooter: { next: 'Next', prev: 'Previous' },
				editLink: {
					pattern: 'https://github.com/saqqdy/directix/edit/master/docs/:path',
					text: 'Edit this page on GitHub',
				},
				footer: {
					copyright: 'Copyright © 2024-present saqqdy',
					message: 'Released under the MIT License.',
				},
				langMenuLabel: 'Language',
				lastUpdated: {
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
					text: 'Last updated',
				},
				lightModeSwitchTitle: 'Switch to light theme',
				nav: [
					{ activeMatch: '/guide/', link: '/guide/', text: 'Guide' },
					{ link: '/playground', text: 'Playground' },
					{ activeMatch: '/api/', link: '/api/', text: 'API' },
					{ activeMatch: '/examples/', link: '/examples/', text: 'Examples' },
					{
						items: [
							{ link: 'https://github.com/saqqdy/directix', text: 'GitHub' },
							{ link: 'https://www.npmjs.com/package/directix', text: 'NPM' },
						],
						text: 'Links',
					},
				],
				outline: { label: 'On this page' },
				returnToTopLabel: 'Return to top',
				sidebar: {
					'/api/': [
						{
							items: [{ link: '/api/', text: 'Overview' }],
							text: 'API Reference',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/click-outside', text: 'v-click-outside' },
								{ link: '/api/directives/click-delay', text: 'v-click-delay' },
								{ link: '/api/directives/click-wave', text: 'v-click-wave' },
								{ link: '/api/directives/context-menu', text: 'v-context-menu' },
								{ link: '/api/directives/debounce', text: 'v-debounce' },
								{ link: '/api/directives/throttle', text: 'v-throttle' },
								{ link: '/api/directives/long-press', text: 'v-long-press' },
								{ link: '/api/directives/hover', text: 'v-hover' },
								{ link: '/api/directives/ripple', text: 'v-ripple' },
								{ link: '/api/directives/touch', text: 'v-touch' },
								{ link: '/api/directives/swipe', text: 'v-swipe' },
								{ link: '/api/directives/hotkey', text: 'v-hotkey' },
							],
							text: 'Event Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/lazy', text: 'v-lazy' },
								{ link: '/api/directives/intersect', text: 'v-intersect' },
								{ link: '/api/directives/visible', text: 'v-visible' },
								{ link: '/api/directives/loading', text: 'v-loading' },
								{ link: '/api/directives/image-preview', text: 'v-image-preview' },
							],
							text: 'Visibility Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/scroll', text: 'v-scroll' },
								{ link: '/api/directives/infinite-scroll', text: 'v-infinite-scroll' },
								{ link: '/api/directives/sticky', text: 'v-sticky' },
								{ link: '/api/directives/pull-refresh', text: 'v-pull-refresh' },
								{ link: '/api/directives/virtual-list', text: 'v-virtual-list' },
								{ link: '/api/directives/parallax', text: 'v-parallax' },
							],
							text: 'Scroll Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/copy', text: 'v-copy' },
								{ link: '/api/directives/focus', text: 'v-focus' },
								{ link: '/api/directives/mask', text: 'v-mask' },
								{ link: '/api/directives/trim', text: 'v-trim' },
								{ link: '/api/directives/capitalcase', text: 'v-capitalcase' },
								{ link: '/api/directives/lowercase', text: 'v-lowercase' },
								{ link: '/api/directives/uppercase', text: 'v-uppercase' },
								{ link: '/api/directives/money', text: 'v-money' },
								{ link: '/api/directives/number', text: 'v-number' },
								{ link: '/api/directives/emoji', text: 'v-emoji' },
							],
							text: 'Form Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/tooltip', text: 'v-tooltip' },
								{ link: '/api/directives/draggable', text: 'v-draggable' },
								{ link: '/api/directives/truncate', text: 'v-truncate' },
								{ link: '/api/directives/ellipsis', text: 'v-ellipsis' },
								{ link: '/api/directives/watermark', text: 'v-watermark' },
								{ link: '/api/directives/print', text: 'v-print' },
								{ link: '/api/directives/virtual-list', text: 'v-virtual-list' },
								{ link: '/api/directives/countdown', text: 'v-countdown' },
								{ link: '/api/directives/blur', text: 'v-blur' },
								{ link: '/api/directives/counter', text: 'v-counter' },
								{ link: '/api/directives/export', text: 'v-export' },
								{ link: '/api/directives/fade', text: 'v-fade' },
								{ link: '/api/directives/fullscreen', text: 'v-fullscreen' },
								{ link: '/api/directives/highlight', text: 'v-highlight' },
								{ link: '/api/directives/lottie', text: 'v-lottie' },
								{ link: '/api/directives/progress', text: 'v-progress' },
								{ link: '/api/directives/skeleton', text: 'v-skeleton' },
								{ link: '/api/directives/typewriter', text: 'v-typewriter' },
							],
							text: 'UI Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/permission', text: 'v-permission' },
								{ link: '/api/directives/sanitize', text: 'v-sanitize' },
							],
							text: 'Security Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/resize', text: 'v-resize' },
								{ link: '/api/directives/mutation', text: 'v-mutation' },
							],
							text: 'Observer Directives',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/directives/pan', text: 'v-pan' },
								{ link: '/api/directives/pinch', text: 'v-pinch' },
								{ link: '/api/directives/rotate-gesture', text: 'v-rotate-gesture' },
							],
							text: 'Gesture Directives',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-click-outside', text: 'useClickOutside' },
								{ link: '/api/composables/use-click-delay', text: 'useClickDelay' },
								{ link: '/api/composables/use-debounce', text: 'useDebounce' },
								{ link: '/api/composables/use-throttle', text: 'useThrottle' },
								{ link: '/api/composables/use-long-press', text: 'useLongPress' },
								{ link: '/api/composables/use-hover', text: 'useHover' },
								{ link: '/api/composables/use-ripple', text: 'useRipple' },
								{ link: '/api/composables/use-touch', text: 'useTouch' },
								{ link: '/api/composables/use-swipe', text: 'useSwipe' },
								{ link: '/api/composables/use-hotkey', text: 'useHotkey' },
							],
							text: 'Event Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-lazy', text: 'useLazy' },
								{ link: '/api/composables/use-intersect', text: 'useIntersect' },
								{ link: '/api/composables/use-visible', text: 'useVisible' },
								{ link: '/api/composables/use-loading', text: 'useLoading' },
								{ link: '/api/composables/use-image-preview', text: 'useImagePreview' },
							],
							text: 'Visibility Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-scroll', text: 'useScroll' },
								{ link: '/api/composables/use-infinite-scroll', text: 'useInfiniteScroll' },
								{ link: '/api/composables/use-sticky', text: 'useSticky' },
								{ link: '/api/composables/use-pull-refresh', text: 'usePullRefresh' },
								{ link: '/api/composables/use-virtual-list', text: 'useVirtualList' },
							],
							text: 'Scroll Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-copy', text: 'useCopy' },
								{ link: '/api/composables/use-focus', text: 'useFocus' },
								{ link: '/api/composables/use-mask', text: 'useMask' },
								{ link: '/api/composables/use-trim', text: 'useTrim' },
								{ link: '/api/composables/use-capitalcase', text: 'useCapitalcase' },
								{ link: '/api/composables/use-lowercase', text: 'useLowercase' },
								{ link: '/api/composables/use-uppercase', text: 'useUppercase' },
								{ link: '/api/composables/use-money', text: 'useMoney' },
								{ link: '/api/composables/use-number', text: 'useNumber' },
							],
							text: 'Form Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-tooltip', text: 'useTooltip' },
								{ link: '/api/composables/use-draggable', text: 'useDraggable' },
								{ link: '/api/composables/use-truncate', text: 'useTruncate' },
								{ link: '/api/composables/use-ellipsis', text: 'useEllipsis' },
								{ link: '/api/composables/use-watermark', text: 'useWatermark' },
								{ link: '/api/composables/use-print', text: 'usePrint' },
								{ link: '/api/composables/use-virtual-list', text: 'useVirtualList' },
								{ link: '/api/composables/use-countdown', text: 'useCountdown' },
							],
							text: 'UI Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-permission', text: 'usePermission' },
								{ link: '/api/composables/use-sanitize', text: 'useSanitize' },
							],
							text: 'Security Composables',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/composables/use-resize', text: 'useResize' },
								{ link: '/api/composables/use-mutation', text: 'useMutation' },
							],
							text: 'Observer Composables',
						},
					],
					'/examples/': [
						{
							items: [{ link: '/examples/', text: 'Overview' }],
							text: 'Examples',
						},
						{
							items: [
								{ link: '/examples/click-outside', text: 'Click Outside' },
								{ link: '/examples/copy', text: 'Copy' },
								{ link: '/examples/debounce', text: 'Debounce' },
								{ link: '/examples/throttle', text: 'Throttle' },
								{ link: '/examples/focus', text: 'Focus' },
							],
							text: 'Demos',
						},
						{
							items: [
								{ link: '/examples/scenarios', text: 'Scenario Examples' },
							],
							text: 'Scenarios',
						},
					],
					'/guide/': [
						{
							items: [
								{ link: '/guide/', text: 'Introduction' },
								{ link: '/guide/installation', text: 'Installation' },
								{ link: '/guide/quick-start', text: 'Quick Start' },
								{ link: '/guide/nuxt', text: 'Nuxt Module' },
								{ link: '/guide/i18n', text: 'Internationalization' },
								{ link: '/guide/plugin', text: 'Plugin System' },
								{ link: '/guide/vscode-extension', text: 'VS Code Extension' },
							],
							text: 'Getting Started',
						},
						{
							items: [
								{ link: '/guide/events', text: 'Event Directives' },
								{ link: '/guide/visibility', text: 'Visibility Directives' },
								{ link: '/guide/scroll', text: 'Scroll Directives' },
								{ link: '/guide/forms', text: 'Form Directives' },
								{ link: '/guide/security', text: 'Security Directives' },
								{ link: '/guide/observers', text: 'Observer Directives' },
							],
							text: 'Categories',
						},
					],
				},
				sidebarMenuLabel: 'Menu',
			},
			title: 'Directix',
		},
		zh: {
			description: '支持 Vue 2 和 Vue 3 的 Vue 指令库',
			label: '简体中文',
			lang: 'zh-CN',
			link: '/zh/',
			themeConfig: {
				darkModeSwitchLabel: '主题',
				darkModeSwitchTitle: '切换到深色模式',
				docFooter: { next: '下一页', prev: '上一页' },
				editLink: {
					pattern: 'https://github.com/saqqdy/directix/edit/master/docs/:path',
					text: '在 GitHub 上编辑此页',
				},
				footer: {
					copyright: '版权所有 © 2024-present saqqdy',
					message: '基于 MIT 许可发布',
				},
				langMenuLabel: '语言',
				lastUpdated: {
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
					text: '最后更新于',
				},
				lightModeSwitchTitle: '切换到浅色模式',
				nav: [
					{ activeMatch: '/zh/guide/', link: '/zh/guide/', text: '指南' },
					{ link: '/zh/playground', text: 'Playground' },
					{ activeMatch: '/zh/api/', link: '/zh/api/', text: 'API' },
					{ activeMatch: '/zh/examples/', link: '/zh/examples/', text: '示例' },
					{
						items: [
							{ link: 'https://github.com/saqqdy/directix', text: 'GitHub' },
							{ link: 'https://www.npmjs.com/package/directix', text: 'NPM' },
						],
						text: '链接',
					},
				],
				outline: { label: '页面导航' },
				returnToTopLabel: '回到顶部',
				sidebar: {
					'/zh/api/': [
						{
							items: [{ link: '/zh/api/', text: '概览' }],
							text: 'API 参考',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/click-outside', text: 'v-click-outside' },
								{ link: '/zh/api/directives/click-delay', text: 'v-click-delay' },
								{ link: '/zh/api/directives/click-wave', text: 'v-click-wave' },
								{ link: '/zh/api/directives/context-menu', text: 'v-context-menu' },
								{ link: '/zh/api/directives/debounce', text: 'v-debounce' },
								{ link: '/zh/api/directives/throttle', text: 'v-throttle' },
								{ link: '/zh/api/directives/long-press', text: 'v-long-press' },
								{ link: '/zh/api/directives/hover', text: 'v-hover' },
								{ link: '/zh/api/directives/ripple', text: 'v-ripple' },
								{ link: '/zh/api/directives/touch', text: 'v-touch' },
								{ link: '/zh/api/directives/swipe', text: 'v-swipe' },
								{ link: '/zh/api/directives/hotkey', text: 'v-hotkey' },
							],
							text: '事件指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/lazy', text: 'v-lazy' },
								{ link: '/zh/api/directives/intersect', text: 'v-intersect' },
								{ link: '/zh/api/directives/visible', text: 'v-visible' },
								{ link: '/zh/api/directives/loading', text: 'v-loading' },
								{ link: '/zh/api/directives/image-preview', text: 'v-image-preview' },
							],
							text: '可见性指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/scroll', text: 'v-scroll' },
								{ link: '/zh/api/directives/infinite-scroll', text: 'v-infinite-scroll' },
								{ link: '/zh/api/directives/sticky', text: 'v-sticky' },
								{ link: '/zh/api/directives/pull-refresh', text: 'v-pull-refresh' },
								{ link: '/zh/api/directives/virtual-list', text: 'v-virtual-list' },
								{ link: '/zh/api/directives/parallax', text: 'v-parallax' },
							],
							text: '滚动指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/copy', text: 'v-copy' },
								{ link: '/zh/api/directives/focus', text: 'v-focus' },
								{ link: '/zh/api/directives/mask', text: 'v-mask' },
								{ link: '/zh/api/directives/trim', text: 'v-trim' },
								{ link: '/zh/api/directives/capitalcase', text: 'v-capitalcase' },
								{ link: '/zh/api/directives/lowercase', text: 'v-lowercase' },
								{ link: '/zh/api/directives/uppercase', text: 'v-uppercase' },
								{ link: '/zh/api/directives/money', text: 'v-money' },
								{ link: '/zh/api/directives/number', text: 'v-number' },
								{ link: '/zh/api/directives/emoji', text: 'v-emoji' },
							],
							text: '表单指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/tooltip', text: 'v-tooltip' },
								{ link: '/zh/api/directives/draggable', text: 'v-draggable' },
								{ link: '/zh/api/directives/truncate', text: 'v-truncate' },
								{ link: '/zh/api/directives/ellipsis', text: 'v-ellipsis' },
								{ link: '/zh/api/directives/watermark', text: 'v-watermark' },
								{ link: '/zh/api/directives/print', text: 'v-print' },
								{ link: '/zh/api/directives/virtual-list', text: 'v-virtual-list' },
								{ link: '/zh/api/directives/countdown', text: 'v-countdown' },
								{ link: '/zh/api/directives/blur', text: 'v-blur' },
								{ link: '/zh/api/directives/counter', text: 'v-counter' },
								{ link: '/zh/api/directives/export', text: 'v-export' },
								{ link: '/zh/api/directives/fade', text: 'v-fade' },
								{ link: '/zh/api/directives/fullscreen', text: 'v-fullscreen' },
								{ link: '/zh/api/directives/highlight', text: 'v-highlight' },
								{ link: '/zh/api/directives/lottie', text: 'v-lottie' },
								{ link: '/zh/api/directives/progress', text: 'v-progress' },
								{ link: '/zh/api/directives/skeleton', text: 'v-skeleton' },
								{ link: '/zh/api/directives/typewriter', text: 'v-typewriter' },
							],
							text: 'UI 指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/permission', text: 'v-permission' },
								{ link: '/zh/api/directives/sanitize', text: 'v-sanitize' },
							],
							text: '安全指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/resize', text: 'v-resize' },
								{ link: '/zh/api/directives/mutation', text: 'v-mutation' },
							],
							text: '观察者指令',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/directives/pan', text: 'v-pan' },
								{ link: '/zh/api/directives/pinch', text: 'v-pinch' },
								{ link: '/zh/api/directives/rotate-gesture', text: 'v-rotate-gesture' },
							],
							text: '手势指令',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-click-outside', text: 'useClickOutside' },
								{ link: '/zh/api/composables/use-click-delay', text: 'useClickDelay' },
								{ link: '/zh/api/composables/use-debounce', text: 'useDebounce' },
								{ link: '/zh/api/composables/use-throttle', text: 'useThrottle' },
								{ link: '/zh/api/composables/use-long-press', text: 'useLongPress' },
								{ link: '/zh/api/composables/use-hover', text: 'useHover' },
								{ link: '/zh/api/composables/use-ripple', text: 'useRipple' },
								{ link: '/zh/api/composables/use-touch', text: 'useTouch' },
								{ link: '/zh/api/composables/use-swipe', text: 'useSwipe' },
								{ link: '/zh/api/composables/use-hotkey', text: 'useHotkey' },
							],
							text: '事件组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-lazy', text: 'useLazy' },
								{ link: '/zh/api/composables/use-intersect', text: 'useIntersect' },
								{ link: '/zh/api/composables/use-visible', text: 'useVisible' },
								{ link: '/zh/api/composables/use-loading', text: 'useLoading' },
								{ link: '/zh/api/composables/use-image-preview', text: 'useImagePreview' },
							],
							text: '可见性组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-scroll', text: 'useScroll' },
								{ link: '/zh/api/composables/use-infinite-scroll', text: 'useInfiniteScroll' },
								{ link: '/zh/api/composables/use-sticky', text: 'useSticky' },
								{ link: '/zh/api/composables/use-pull-refresh', text: 'usePullRefresh' },
								{ link: '/zh/api/composables/use-virtual-list', text: 'useVirtualList' },
							],
							text: '滚动组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-copy', text: 'useCopy' },
								{ link: '/zh/api/composables/use-focus', text: 'useFocus' },
								{ link: '/zh/api/composables/use-mask', text: 'useMask' },
								{ link: '/zh/api/composables/use-trim', text: 'useTrim' },
								{ link: '/zh/api/composables/use-capitalcase', text: 'useCapitalcase' },
								{ link: '/zh/api/composables/use-lowercase', text: 'useLowercase' },
								{ link: '/zh/api/composables/use-uppercase', text: 'useUppercase' },
								{ link: '/zh/api/composables/use-money', text: 'useMoney' },
								{ link: '/zh/api/composables/use-number', text: 'useNumber' },
							],
							text: '表单组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-tooltip', text: 'useTooltip' },
								{ link: '/zh/api/composables/use-draggable', text: 'useDraggable' },
								{ link: '/zh/api/composables/use-truncate', text: 'useTruncate' },
								{ link: '/zh/api/composables/use-ellipsis', text: 'useEllipsis' },
								{ link: '/zh/api/composables/use-watermark', text: 'useWatermark' },
								{ link: '/zh/api/composables/use-print', text: 'usePrint' },
								{ link: '/zh/api/composables/use-virtual-list', text: 'useVirtualList' },
								{ link: '/zh/api/composables/use-countdown', text: 'useCountdown' },
							],
							text: 'UI 组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-permission', text: 'usePermission' },
								{ link: '/zh/api/composables/use-sanitize', text: 'useSanitize' },
							],
							text: '安全组合式函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/composables/use-resize', text: 'useResize' },
								{ link: '/zh/api/composables/use-mutation', text: 'useMutation' },
							],
							text: '观察者组合式函数',
						},
					],
					'/zh/examples/': [
						{
							items: [{ link: '/zh/examples/', text: '概览' }],
							text: '示例',
						},
						{
							items: [
								{ link: '/zh/examples/click-outside', text: 'Click Outside' },
								{ link: '/zh/examples/copy', text: 'Copy' },
								{ link: '/zh/examples/debounce', text: 'Debounce' },
								{ link: '/zh/examples/throttle', text: 'Throttle' },
								{ link: '/zh/examples/focus', text: 'Focus' },
							],
							text: '演示',
						},
						{
							items: [
								{ link: '/zh/examples/scenarios', text: '场景示例' },
							],
							text: '场景',
						},
					],
					'/zh/guide/': [
						{
							items: [
								{ link: '/zh/guide/', text: '介绍' },
								{ link: '/zh/guide/installation', text: '安装' },
								{ link: '/zh/guide/quick-start', text: '快速上手' },
								{ link: '/zh/guide/nuxt', text: 'Nuxt 模块' },
								{ link: '/zh/guide/i18n', text: '国际化' },
								{ link: '/zh/guide/plugin', text: '插件系统' },
								{ link: '/zh/guide/vscode-extension', text: 'VS Code 插件' },
							],
							text: '开始',
						},
						{
							items: [
								{ link: '/zh/guide/events', text: '事件指令' },
								{ link: '/zh/guide/visibility', text: '可见性指令' },
								{ link: '/zh/guide/scroll', text: '滚动指令' },
								{ link: '/zh/guide/forms', text: '表单指令' },
								{ link: '/zh/guide/security', text: '安全指令' },
								{ link: '/zh/guide/observers', text: '观察者指令' },
							],
							text: '分类',
						},
					],
				},
				sidebarMenuLabel: '菜单',
			},
			title: 'Directix',
		},
	},

	themeConfig: {
		logo: '/logo.svg',
		search: {
			provider: 'local',
		},
		siteTitle: 'Directix',
		socialLinks: [{ icon: 'github', link: 'https://github.com/saqqdy/directix' }],
	},

	title: 'Directix',
})
